#!/usr/bin/env python3
"""The Tux InVader from the project folder: the same commands as the AppImage (try --help)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from vader5.launch import main

sys.exit(main())
